const servicesData = [
  {
    id: 1,
    group: "first",
    titleKey: "usluga 1",
    descriptionKey: "usluga 1 opis",
    icon: "././ikonice-PNG/1_Specijalisticki_pregledi@2x.png",
    iconPosition: "before",
  },
  { id: 2, group: "first", titleKey: "usluga 2", descriptionKey: "usluga 2 opis" },
  { id: 3, group: "first", titleKey: "usluga 3", descriptionKey: "usluga 3 opis" },
  { id: 4, group: "first", titleKey: "usluga 4", descriptionKey: "usluga 4 opis" },
  {
    id: 5,
    group: "first",
    titleKey: "usluga 5",
    descriptionKey: "usluga 5 opis",
    icon: "././ikonice-PNG/Medicinska_hrana+lekovi@2x.png",
    iconPosition: "before",
  },
  {
    id: 6,
    group: "first",
    titleKey: "usluga 6",
    descriptionKey: "usluga 6 opis",
    icon: "././ikonice-PNG/pasport.png",
    iconPosition: "before",
  },
  {
    id: 7,
    group: "first",
    titleKey: "usluga 7",
    descriptionKey: "usluga 7 opis",
    icon: "././ikonice-PNG/Laboratorija@2x.png",
    iconPosition: "before",
  },
  { id: 8, group: "first", titleKey: "usluga 8", descriptionKey: "usluga 8 opis" },
  { id: 9, group: "first", titleKey: "usluga 9", descriptionKey: "usluga 9 opis" },
  { id: 10, group: "second", titleKey: "usluga 10", descriptionKey: "usluga 10 opis" },
  { id: 11, group: "second", titleKey: "usluga 11", descriptionKey: "usluga 11 opis" },
  { id: 12, group: "second", titleKey: "usluga 12", descriptionKey: "usluga 12 opis" },
  { id: 13, group: "second", titleKey: "usluga 13", descriptionKey: "usluga 13 opis" },
  { id: 14, group: "second", titleKey: "usluga 14", descriptionKey: "usluga 14 opis" },
  {
    id: 15,
    group: "second",
    titleKey: "usluga 15",
    descriptionKey: "usluga 15 opis",
    icon: "././ikonice-PNG/paraziti@2x.png",
    iconPosition: "after",
  },
  { id: 16, group: "second", titleKey: "usluga 16", descriptionKey: "usluga 16 opis" },
  { id: 17, group: "second", titleKey: "usluga 17", descriptionKey: "usluga 17 opis" },
  { id: 18, group: "second", titleKey: "usluga 18", descriptionKey: "usluga 18 opis" },
  {
    id: 19,
    group: "third",
    titleKey: "usluga 19",
    descriptionKey: "usluga 19 opis",
    icon: "././ikonice-PNG/hirurgija@2x.png",
    iconPosition: "after",
  },
  { id: 20, group: "third", titleKey: "usluga 20", descriptionKey: "usluga 20 opis" },
  { id: 21, group: "third", titleKey: "usluga 21", descriptionKey: "usluga 21 opis" },
  { id: 22, group: "third", titleKey: "usluga 22", descriptionKey: "usluga 22 opis" },
  {
    id: 25,
    group: "third",
    titleKey: "usluga 25",
    descriptionKey: "usluga 25 opis",
    icon: "././ikonice-PNG/egzoticni_ljubimci@2x.png",
    iconPosition: "before",
  },
  {
    id: 26,
    group: "third",
    titleKey: "usluga 26",
    descriptionKey: "usluga 26 opis",
    icon: "././ikonice-PNG/ultrazvuk@2x.png",
    iconPosition: "before",
  },
  {
    id: 27,
    group: "third",
    titleKey: "usluga 27",
    descriptionKey: "usluga 27 opis",
    icon: "././ikonice-PNG/rentgen@2x.png",
    iconPosition: "before",
  },
  {
    id: 28,
    group: "third",
    titleKey: "usluga 28",
    descriptionKey: "usluga 28 opis",
    icon: "././ikonice-PNG/magnet@2x.png",
    iconPosition: "before",
  },
  {
    id: 29,
    group: "third",
    titleKey: "usluga 29",
    descriptionKey: "usluga 29 opis",
    icon: "././ikonice-PNG/kupanje_i_sisanje@2x.png",
    iconPosition: "before",
  },
  {
    id: 30,
    group: "third",
    titleKey: "usluga 30",
    descriptionKey: "usluga 30 opis",
    icon: "././ikonice-PNG/hrana+lekovi@2x.png",
    iconPosition: "before",
  },
];

export default servicesData;
